{
 "title": "Kyverno",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Kyverno\nA Kubernetes-native policy management engine\n\n#### About this dashboard\n\nThis dashboard represents generic insights which can be extracted and made well use of from a cluster with Kyverno in action.\n\n#### For more details around the metrics\n\nCheckout the [official docs of Kyverno metrics](https://kyverno.io/docs/monitoring-kyverno-with-prometheus-metrics/)"
   }
  },
  { "title": "Latest Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Rule Execution Success Rate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kyverno_policy_results_total{rule_result=\"pass\"})*100/sum(kyverno_policy_results_total{})"
    }
   ]
  },
  {
   "title": "Cluster Policies",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(kyverno_policy_rule_info_total{policy_type=\"cluster\"}==1) by (policy_name))"
    }
   ]
  },
  {
   "title": "Policies",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(kyverno_policy_rule_info_total{policy_type=\"namespaced\"}==1) by (policy_name))"
    }
   ]
  },
  {
   "title": "Background Scans Success Rate",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kyverno_policy_results_total{rule_result=\"pass\", policy_background_mode=\"true\"})*100/sum(kyverno_policy_results_total{policy_background_mode=\"true\"})"
    }
   ]
  },
  {
   "title": "Validate Rules",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kyverno_policy_rule_info_total{rule_type=\"validate\"}==1)"
    }
   ]
  },
  {
   "title": "Mutate Rules",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kyverno_policy_rule_info_total{rule_type=\"mutate\"}==1)"
    }
   ]
  },
  {
   "title": "Generate Rules",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kyverno_policy_rule_info_total{rule_type=\"generate\"}==1)"
    }
   ]
  },
  { "title": "Policy-Rule Results", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Admission Review Results (per-rule)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kyverno_policy_results_total{rule_execution_cause=\"admission_request\"}) by (rule_result)",
     "legendFormat": "{{rule_result}}"
    }
   ]
  },
  {
   "title": "Background Scan Results (per-rule)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kyverno_policy_results_total{rule_execution_cause=\"background_scan\"}) by (rule_result)",
     "legendFormat": "{{rule_result}}"
    }
   ]
  },
  {
   "title": "Policy Failures",
   "type": "graph",
   "gridPos": { "h": 16, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum(kyverno_policy_results_total{rule_result=\"fail\"}) by (policy_name, policy_type)) by (policy_type)",
     "legendFormat": "{{policy_type}}"
    }
   ]
  },
  {
   "title": "Admission Review Results (per-policy)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum(kyverno_policy_results_total{rule_execution_cause=\"admission_request\"}) by (policy_name, rule_result)) by (rule_result)",
     "legendFormat": "{{rule_result}}"
    }
   ]
  },
  {
   "title": "Background Scan Results (per-policy)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum(kyverno_policy_results_total{rule_execution_cause=\"background_scan\"}) by (policy_name, rule_result)) by (rule_result)",
     "legendFormat": "{{rule_result}}"
    }
   ]
  },
  { "title": "Policy-Rule Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Active Policies (by policy type)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(count(kyverno_policy_rule_info_total{}==1) by (policy_name, policy_type)) by (policy_type)",
     "legendFormat": "{{policy_type}}"
    }
   ]
  },
  {
   "title": "Active Policies (by policy validation action)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(count(kyverno_policy_rule_info_total{}==1) by (policy_name, policy_validation_mode)) by (policy_validation_mode)",
     "legendFormat": "audit"
    }
   ]
  },
  {
   "title": "Active Policies running in background mode",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(count(kyverno_policy_rule_info_total{policy_background_mode=\"true\"}==1) by (policy_name, policy_type)) by (policy_type)",
     "legendFormat": "{{policy_type}}"
    }
   ]
  },
  {
   "title": "Active Namespaced Policies (by namespaces)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(count(kyverno_policy_rule_info_total{policy_namespace!=\"-\"}==1) by (policy_name, policy_namespace)) by (policy_namespace)",
     "legendFormat": "{{policy_namespace}}"
    }
   ]
  },
  {
   "title": "Active Rules (by rule type)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kyverno_policy_rule_info_total{}==1) by (rule_type)",
     "legendFormat": "{{rule_type}}"
    }
   ]
  },
  { "title": "Policy-Rule Execution Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Average Rule Execution Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(kyverno_policy_execution_duration_seconds_sum{}) by (rule_type)",
     "legendFormat": "{{rule_type}}"
    }
   ]
  },
  {
   "title": "Average Policy Execution Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 51 },
   "yaxes": [
    { "format": "clocks" }
   ],
   "targets": [
    {
     "expr": "avg(sum(kyverno_policy_execution_duration_seconds_sum{}) by (policy_name, policy_type)) by (policy_type)",
     "legendFormat": "{{policy_type}}"
    }
   ]
  },
  {
   "title": "Overall Average Rule Execution Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kyverno_policy_execution_duration_seconds_sum{})"
    }
   ]
  },
  {
   "title": "Overall Average Policy Execution Latency",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum(kyverno_policy_execution_duration_seconds_sum{}) by (policy_name, policy_type))"
    }
   ]
  },
  { "title": "Admission Review Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Avg - Admission Review Duration (by operation)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(kyverno_admission_requests_total{}) by (resource_request_operation)",
     "legendFormat": "Resource Operation: {{resource_request_operation}}"
    }
   ]
  },
  {
   "title": "Avg - Admission Review Duration (by resource kind)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 60 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(kyverno_admission_requests_total{}) by (resource_kind)",
     "legendFormat": "Resource Kind: {{resource_kind}}"
    }
   ]
  },
  {
   "title": "Rate - Incoming Admission Requests (last 5m)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(kyverno_admission_requests_total{}[5m]))"
    }
   ]
  },
  {
   "title": "Avg - Overall Admission Review Duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kyverno_admission_review_duration_seconds_sum{})"
    }
   ]
  },
  { "title": "Policy Changes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "Policy Changes (by change type)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kyverno_policy_changes_total{}) by (policy_change_type)",
     "legendFormat": "Change type: {{policy_change_type}}"
    }
   ]
  },
  {
   "title": "Policy Changes (by policy type)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 69 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kyverno_policy_changes_total{}) by (policy_type)",
     "legendFormat": "{{policy_type}}"
    }
   ]
  },
  {
   "title": "Total Policy Changes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kyverno_policy_changes_total{})"
    }
   ]
  },
  {
   "title": "Rate - Policy Changes Happening (last 5m)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(kyverno_admission_requests_total{}[5m]))"
    }
   ]
  },
  { "title": "Admission Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "Admission Requests (by operation)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kyverno_admission_requests_total{}) by (resource_request_operation)",
     "legendFormat": "Resource Operation: {{resource_request_operation}}"
    }
   ]
  },
  {
   "title": "Admission Requests (by resource kind)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 78 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kyverno_admission_requests_total{}) by (resource_kind)",
     "legendFormat": "Resource Kind: {{resource_kind}}"
    }
   ]
  },
  {
   "title": "Total Admission Requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kyverno_admission_requests_total{})"
    }
   ]
  }
 ]
}
{
 "title": "NGINX Ingress",
 "description": "Ingress-nginx supports a rich collection of prometheus metrics. If you have prometheus and grafana installed on your cluster then prometheus will already be scraping this data due to the scrape annotation on the deployment.",
 "tags": [ "nginx" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(nginx_ingress_controller_config_hash, controller_namespace)"
    }
   },
   {
    "name": "controller_class",
    "label": "Controller Class",
    "query": {
     "query": "label_values(nginx_ingress_controller_config_hash{namespace=~\"$namespace\"}, controller_class) "
    }
   },
   {
    "name": "controller",
    "label": "Controller",
    "query": {
     "query": "label_values(nginx_ingress_controller_config_hash{namespace=~\"$namespace\",controller_class=~\"$controller_class\"}, controller_pod) "
    }
   },
   {
    "name": "ingress",
    "label": "Ingress",
    "query": {
     "query": "label_values(nginx_ingress_controller_requests{namespace=~\"$namespace\",controller_class=~\"$controller_class\",controller=~\"$controller\"}, ingress) "
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Controller Request Volume",
   "type": "stat",
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "round(sum(irate(nginx_ingress_controller_requests{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",namespace=~\"$namespace\"}[2m])), 0.001)"
    }
   ]
  },
  {
   "title": "Controller Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(nginx_ingress_controller_nginx_process_connections{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\"}[2m]))"
    }
   ]
  },
  {
   "title": "Controller Success Rate (non-4|5xx responses)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",namespace=~\"$namespace\",status!~\"[4-5].*\"}[2m])) / sum(rate(nginx_ingress_controller_requests{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",namespace=~\"$namespace\"}[2m]))"
    }
   ]
  },
  {
   "title": "Config Reloads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(nginx_ingress_controller_success{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Last Config Failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(nginx_ingress_controller_config_last_reload_successful{controller_pod=~\"$controller\",controller_namespace=~\"$namespace\"} == 0)"
    }
   ]
  },
  {
   "title": "Ingress Request Volume",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "round(sum(irate(nginx_ingress_controller_requests{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\",ingress=~\"$ingress\"}[2m])) by (ingress), 0.001)",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "Ingress Success Rate (non-4|5xx responses)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",namespace=~\"$namespace\",ingress=~\"$ingress\",status!~\"[4-5].*\"}[2m])) by (ingress) / sum(rate(nginx_ingress_controller_requests{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",namespace=~\"$namespace\",ingress=~\"$ingress\"}[2m])) by (ingress)",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "Network I/O pressure",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (irate (nginx_ingress_controller_request_size_sum{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\"}[2m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "- sum (irate (nginx_ingress_controller_response_size_sum{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\"}[2m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Average Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(nginx_ingress_controller_nginx_process_resident_memory_bytes{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\"}) ",
     "legendFormat": "nginx"
    }
   ]
  },
  {
   "title": "Average CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (nginx_ingress_controller_nginx_process_cpu_seconds_total{controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\"}[2m])) ",
     "legendFormat": "nginx"
    }
   ]
  },
  {
   "title": "Ingress Percentile Response Times and Transfer Rates",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress!=\"\",controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\",ingress=~\"$ingress\"}[2m])) by (le, ingress))",
     "legendFormat": "{{ ingress }}"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress!=\"\",controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\",ingress=~\"$ingress\"}[2m])) by (le, ingress))",
     "legendFormat": "{{ ingress }}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress!=\"\",controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\",ingress=~\"$ingress\"}[2m])) by (le, ingress))",
     "legendFormat": "{{ destination_service }}"
    },
    {
     "expr": "sum(irate(nginx_ingress_controller_request_size_sum{ingress!=\"\",controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\",ingress=~\"$ingress\"}[2m])) by (ingress)",
     "legendFormat": "{{ ingress }}"
    },
    {
     "expr": "sum(irate(nginx_ingress_controller_response_size_sum{ingress!=\"\",controller_pod=~\"$controller\",controller_class=~\"$controller_class\",controller_namespace=~\"$namespace\",ingress=~\"$ingress\"}[2m])) by (ingress)",
     "legendFormat": "{{ ingress }}"
    }
   ]
  },
  {
   "title": "Ingress Certificate Expiry",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "avg(nginx_ingress_controller_ssl_expire_time_seconds{kubernetes_pod_name=~\"$controller\",namespace=~\"$namespace\",ingress=~\"$ingress\"}) by (host) - time()",
     "legendFormat": "{{ host }}"
    }
   ]
  }
 ]
}
{
 "title": "Metallb",
 "description": "Metallb key metrics",
 "tags": [
  "metallb ",
  "prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "layer2instance",
    "label": "Layer 2 instance",
    "query": {
     "query": "label_values(metallb_layer2_gratuitous_sent,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Address utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "metallb_allocator_addresses_total"
    },
    {
     "expr": "metallb_allocator_addresses_in_use_total"
    }
   ]
  },
  {
   "title": "Stale config",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(metallb_k8s_client_config_stale_bool)",
     "legendFormat": "client_config_stale"
    }
   ]
  },
  {
   "title": "Layer 2",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(metallb_layer2_gratuitous_sent{instance=~\"$layer2instance\"}[5m])",
     "legendFormat": "gratuitous_sent instance={{instance}} ip={{ip}} "
    },
    {
     "expr": "rate(metallb_layer2_requests_received{instance=~\"$layer2instance\"}[5m])",
     "legendFormat": "requests_received instance={{instance}} ip={{ip}} "
    },
    {
     "expr": "rate(metallb_layer2_responses_sent{instance=~\"$layer2instance\"}[5m])",
     "legendFormat": "responses_sent instance={{instance}} ip={{ip}} "
    }
   ]
  },
  {
   "title": "Client updates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(metallb_k8s_client_update_errors_total[5m])"
    },
    {
     "expr": "rate(metallb_k8s_client_updates_total[5m])"
    }
   ]
  }
 ]
}
{
 "title": "kube apiserver",
 "description": "Latency and cache hit graphs for Kubernetes apiserver.  Useful for observing performance of Amazon EKS clusters.",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "apiserver request rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "req/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total[5m])) by (verb)",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "workqueue service time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s", "label": "service time" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(workqueue_queue_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(workqueue_queue_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(workqueue_queue_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "apiserver request latency",
   "type": "graph",
   "description": "95th percentile request latency for Kubernetes apiserver component",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s", "label": "latency" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(apiserver_request_duration_seconds_bucket{verb!~\"CONNECT|WATCH\"}[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(apiserver_request_duration_seconds_bucket{verb!~\"CONNECT|WATCH\"}[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(apiserver_request_duration_seconds_bucket{verb!~\"CONNECT|WATCH\"}[5m])) by (le))",
     "legendFormat": "p50 "
    }
   ]
  },
  {
   "title": "workqueue processing time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s", "label": "processing time" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(workqueue_work_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(workqueue_work_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(workqueue_work_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "etcd helper cache hit ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_helper_cache_hit_total[5m]))/sum((rate(etcd_helper_cache_hit_total[5m])+rate(etcd_helper_cache_miss_total[5m])))",
     "legendFormat": "ratio"
    }
   ]
  },
  {
   "title": "etcd request latency",
   "type": "graph",
   "description": "etcd request latency (p95)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "s", "label": "latency" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(etcd_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(etcd_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(etcd_request_duration_seconds_bucket[5m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  }
 ]
}
{
 "title": "Falco",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Events rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(falco_events[5m]) > 0",
     "legendFormat": "{{rule}} (node=\"{{kubernetes_node}}\",ns=\"{{k8s_ns_name}}\",pod=\"{{k8s_pod_name}}\")"
    }
   ]
  },
  {
   "title": "Totals",
   "type": "table-old",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "targets": [
    { "expr": "falco_events" }
   ]
  }
 ]
}
{
 "title": "Logs / App",
 "description": "Log Viewer Dashboard for Loki",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "app", "label": "App", "query": "label_values(job)" },
   { "name": "search", "label": "String Match" }
  ]
 },
 "panels": [
  {
   "type": "graph",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({job=\"$app\"} |= \"$search\" [$__interval]))"
    }
   ]
  },
  {
   "type": "logs",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "{job=\"$app\"} |= \"$search\" | logfmt"
    }
   ]
  }
 ]
}
{
 "title": "Loki Quick Search",
 "description": "Loki logs panel with prometheus variables ",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(container_network_receive_bytes_total{namespace=~\"$namespace\"},pod)"
    }
   },
   { "name": "search", "query": "level=warn" }
  ]
 },
 "panels": [
  {
   "type": "graph",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({namespace=\"$namespace\", instance=~\"$pod\"} |~ \"$search\"[$__interval]))"
    }
   ]
  },
  {
   "title": "Logs Panel",
   "type": "logs",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "{namespace=\"$namespace\", instance=~\"$pod\"} |~ \"$search\""
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 28 },
   "options": {
    "content": "<div style=\"text-align:center\"> For Grafana Loki blog example </div>\n\n\n"
   }
  }
 ]
}