apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
nodeRegistration:
  name: "mothership"
  criSocket: "/var/run/dockershim.sock"
localAPIEndpoint:
  advertiseAddress: "192.168.1.211"
  bindPort: 6443
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
networking:
  serviceSubnet: "10.96.0.0/12"
  podSubnet: "10.0.0.0/16"
  dnsDomain: "cluster.local"
kubernetesVersion: "v1.23.3"
controlPlaneEndpoint: "192.168.1.211:6443"
